{paths, ["apps", "deps"]}.

%% comment this line for a release that ships its own Erlang VM
%% {include_erts, false}.
%% uncomment this line to ship a release without the source code included
% {include_src, false}.

{release, {etsdb, VERSION},
 %% list of apps to include
 [etsdb]}.

{extended_start_script, true}.
{sys_config, "./rel/sys.config"}.
{vm_args, "./rel/vm.args"}.
{overlay, [
    {mkdir, "log"}
]}.
