#!/bin/sh

[ -f /etc/default/etsdb ] && . /etc/default/etsdb

mkdir -p /var/lib/etsdb/cluster_meta /var/lib/etsdb/ring

chown -R etsdb /var/lib/etsdb /opt/etsdb/log

su - etsdb /opt/etsdb/bin/etsdb "$@"
